// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ProcessoTest {
  private IWebDriver driver;
  private WebDriverWait wait;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    
    driver = new ChromeDriver();
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);

    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
  }
  [Test]
  public void ShouldReturnASuccessProcessProtocolMessage() {

    wait = new WebDriverWait(driver, new TimeSpan(0, 5, 0));
    wait.IgnoreExceptionTypes(typeof(NoSuchElementException),typeof(InvalidOperationException));

    driver.Navigate().GoToUrl("http://eapresfeature.tce.govrn/");

    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).SendKeys("054.762.524-36");
    driver.FindElement(By.Id("password")).SendKeys("dev@123");
    driver.FindElement(By.Id("idEntrarLogin")).Click();
    driver.FindElement(By.LinkText("Monitoramento")).Click();
    driver.FindElement(By.Id("pendencia")).Click();
    {
      var element = driver.FindElement(By.Id("pendencia"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }

    wait.Until(e => e.FindElement(By.XPath("/html/body/app-root/app-dashboard/div/div/main/app-pendencia-list/section/div[2]/div/div[3]/form/div[1]/table/tbody/tr[1]/td[2]")));

    driver.FindElement(By.Id("selectStatusAutuacao")).Click();
    wait.Until(e => e.FindElement(By.XPath("/html/body/app-root/app-dashboard/div/div/main/app-pendencia-list/section/div[2]/div/div[2]/div/fieldset[2]/form/div/div[6]/ng-select/ng-dropdown-panel/div/div[2]/div[1]/span"))).Click();

    driver.FindElement(By.Id("botaoConsultarPendencia")).Click();

    wait.Until(e => e.FindElement(By.CssSelector(".odd:nth-child(1) .fa-file-text-o")));
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .fa-file-text-o")).Click();
    driver.FindElement(By.CssSelector(".swal2-confirm")).Click();
    
    var actualResult = driver.FindElement(By.XPath("/html/body/div[2]/div/div[2]/div[1]")).Text;
    var expectedResult = "Processo protocolado com sucesso";

    StringAssert.AreEqualIgnoringCase(expectedResult , actualResult);
  }
}
