// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
// using SeleniumExtras;

[TestFixture]
public class ResponsavelPelaApuracaoTest {
  
  
  private IWebDriver driver;
  private WebDriverWait wait;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]

  public void SetUp() {
    
    driver = new ChromeDriver();
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);

    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();

  }

  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
  }

  [Test]
  public void ShouldReturnASuccessCreateMessage() {
    wait = new WebDriverWait(driver, new TimeSpan(0, 10, 0));
    wait.IgnoreExceptionTypes(typeof(NoSuchElementException),typeof(InvalidOperationException));

    driver.Navigate().GoToUrl("http://eapresfeature.tce.govrn/");
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).Click();
    {
      var element = driver.FindElement(By.Id("username"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("username")).SendKeys("054.762.524-36");
    driver.FindElement(By.Id("password")).SendKeys("dev@123");
    driver.FindElement(By.Id("idEntrarLogin")).Click();
    wait.Until(e => e.FindElement(By.LinkText("Cadastros"))).Click();
    wait.Until(e => e.FindElement(By.Id("responsavelApuracao"))).Click();
    
    wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.PresenceOfAllElementsLocatedBy(By.XPath("//*[@id='loading2'][contains(@style, 'display: none')]")));
    //ElementIsVisible(By.Id("content-section")));

    // driver.wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id='loading2'][contains(@style, 'display: none')]")));

    wait.Until(e => e.FindElement(By.Id("botaoCadastrar")));

    wait.Until(e => e.FindElement(By.XPath("/html/body/app-root/app-dashboard/div/div/main/app-responsavelapuracao-list/section/h1/a"))).Click();
// document.querySelector("#botaoCadastrar")
    driver.FindElement(By.Id("selectGrupoUnidadeJurisdicionada")).Click();
    wait.Until(e => e.FindElement(By.XPath("/html/body/app-root/app-dashboard/div/div/main/app-responsavelapuracao-form/div/div/form/fieldset/div[1]/div[1]/div/ng-select/ng-dropdown-panel/div/div[2]/div[2]/span"))).Click();

    driver.FindElement(By.Id("selectObrigacao")).Click();
    wait.Until(e => e.FindElement(By.XPath("/html/body/app-root/app-dashboard/div/div/main/app-responsavelapuracao-form/div/div/form/fieldset/div[1]/div[2]/div/ng-select/ng-dropdown-panel/div/div[2]/div[3]/span"))).Click();

    driver.FindElement(By.Id("selectSetor")).Click();
    wait.Until(e => e.FindElement(By.XPath("/html/body/app-root/app-dashboard/div/div/main/app-responsavelapuracao-form/div/div/form/fieldset/div[2]/div/div/ng-select/ng-dropdown-panel/div/div[2]/div[4]/span"))).Click();

    driver.FindElement(By.Id("idButtonSalvar")).Click();

    wait.Until(e => e.FindElement(By.XPath("/html/body/div[2]/div/div[2]/div[1]")));
    var actualResult = driver.FindElement(By.XPath("/html/body/div[2]/div/div[2]/div[1]")).Text;
    var expectedResult = "Cadastro realizado com sucesso!";

    StringAssert.AreEqualIgnoringCase(expectedResult , actualResult);

  }


}
