// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using UI.PageObjects;

// using SeleniumExtras;

[TestFixture]
public class ResponsavelPelaApuracaoTest {
  
  
  private IWebDriver driver;
  private WebDriverWait wait;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]

  public void SetUp() {
    
    driver = new ChromeDriver();
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);

    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();

  }

  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
  }

  [Test]
  public void ShouldReturnASuccessCreateMessage() {
    wait = new WebDriverWait(driver, new TimeSpan(0, 10, 0));
    wait.IgnoreExceptionTypes(typeof(NoSuchElementException),typeof(InvalidOperationException));

    driver.Navigate().GoToUrl("http://eapresfeature.tce.govrn/");

    LoginTCE login = new LoginTCE("054.762.524-36", "dev@123");
    login.join();
    
    wait.Until(e => e.FindElement(By.LinkText("Cadastros"))).Click();
    wait.Until(e => e.FindElement(By.Id("responsavelApuracao"))).Click();
    
    wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.PresenceOfAllElementsLocatedBy(By.XPath("//*[@id='loading2'][contains(@style, 'display: none')]")));
    
    wait.Until(e => e.FindElement(By.Id("botaoCadastrar")));

    wait.Until(e => e.FindElement(By.XPath("/html/body/app-root/app-dashboard/div/div/main/app-responsavelapuracao-list/section/h1/a"))).Click();

    var group = "Procuradoria Geral de Justiça";
    var responsibility = "Siai DP";
    var sector = "DDP - DIRETORIA DE DESPESA COM PESSOAL";

    ResponsavelPelaApuracaoPO responsavelPO = new ResponsavelPelaApuracaoPO(group, responsibility, sector);
    responsavelPO.register();

    wait.Until(e => e.FindElement(By.XPath("/html/body/div[2]/div/div[2]/div[1]")));
    var actualResult = driver.FindElement(By.XPath("/html/body/div[2]/div/div[2]/div[1]")).Text;
    var expectedResult = "Cadastro realizado com sucesso!";

    StringAssert.AreEqualIgnoringCase(expectedResult , actualResult);

  }


}
